spring.datasource.url = jdbc:mysql://localhost:3306/sistema_inventario?createDatabaseIfNotExist=true

spring.datasource.username = root
spring.datasource.password = root

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# LOGGING (OPCIONAL PARA DEBUG)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

# ===============================
# ERRORES
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# datos para crear un usuario admin del sistema de forma automatica.
app.admin.username=admin
app.admin.password=Admin123*


